# Generated by Django 4.1.3 on 2022-11-29 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 29, 15, 24, 9, 541252, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 29, 15, 24, 9, 541252, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 29, 15, 24, 9, 541252, tzinfo=datetime.timezone.utc)),
        ),
    ]
